apiVersion: v1
kind: Pod
metadata:
  labels:
    run: adminer-test
  name: adminer-test
spec:
  nodeName: toaster
  containers:
  - image: adminer:latest
    name: adminer-test
    ports:
      - containerPort: 8080
