apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec: 
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secret 
            key: access-key 
            namespace: aws
          secretAccessKeySecretRef:
            name: aws-secret
            key: secret-access-key 
            namespace: aws
