apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: homepage
  namespace: test-dev
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: homepage
  service:
    port: 3000
    targetPort: 3000
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
