apiVersion: v1
kind: Service
metadata:
  name: home-svc
  namespace: test-dev 
spec:
  type: NodePort
  ports:
  - name: "web"
    port: 3000
    targetPort: 3000
    nodePort: 30900
  selector:
    app: homepage
