apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: test-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-dev
  name: app-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: test-dev
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: test-dev
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io

