apiVersion: apps/v1
kind: Deployment 
metadata:
  name: pgadmin
  namespace: test-dev 
  labels:
    tier: admin
    app: admin
    env: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      env: pgadmin
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: pgadmin-pod 
      labels:
        env: pgadmin
    spec:
      serviceAccountName: app-sa
      containers:
        - name: pgadmin 
          image: dpage/pgadmin4:9.4.0 
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret 
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: PGADMIN_DEFAULT_PASSWORD
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-claim
      volumes:
        - name: pgadmin-claim
          persistentVolumeClaim:
            claimName: pgadmin-claim

