apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: warden
  name: warden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warden
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: warden
    spec:
      serviceAccountName: app-sa
      containers:
        - envFrom:
            - secretRef:
                name: vaultwarden-env
          image: docker.io/vaultwarden/server:latest
          name: vaultwarden
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
