apiVersion: v1
kind: Service
metadata:
  labels:
    app: warden
  name: warden
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31900
  selector:
    app: warden
