apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: test-dev 
  labels:
    app: homepage 
  name: homepage-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
