apiVersion: v1
kind: Service 
metadata:
  name: warden-svc
  namespace: test-dev 
spec:
  type: ClusterIP
  selector:
    env: security
  ports:
    - name: warden-svc
      port: 80
      targetPort: 80  
