apiVersion: apps/v1
kind: Deployment 
metadata:
  name: warden-deployment 
  namespace: test-dev 
  labels:
    env: security
spec:
  replicas: 2
  selector:
    matchLabels:
      env: security
  template:
    metadata:
      name: warden-rs 
      labels:
        env: security
    spec:
      
      containers:
        - name: vaultwarden-pod 
          image: docker.io/vaultwarden/server:latest
          ports:
          - containerPort: 80
            protocol: TCP
          envFrom:
          - secretRef:
              name: vaultwarden-env

