apiVersion: v1
kind: Pod 
metadata:
  name: nginx
  namespace: mealie
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume 
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep infinity"]
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume 
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
