apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: adminer-rs
  namespace: test-dev 
  labels:
    name: adminer-replicas
    env: data
spec:
  selector:
    matchLabels:
      env: data 
  replicas: 5
  template:
    metadata:
      name: adminer-pod
      labels:
        tier: admin 
        env: data 
    spec:
      containers:
        - name: adminer-pod
          image: adminer:latest
          ports:
            - containerPort: 8080
