apiVersion: apps/v1
kind: Deployment 
metadata:
  name: homepage-deployment 
  namespace: test-dev 
  labels:
    app: homepage 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage 
  template:
    metadata:
      name: homepage-pod 
      labels:
        app: homepage
    spec:
      serviceAccountName: app-sa
      nodeName: toaster
      containers:
      - env:
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: heroaero.dev,www.heroaero.dev
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        image: ghcr.io/gethomepage/homepage:v1.3.2
        imagePullPolicy: ""
        name: homepage
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
      restartPolicy: Always
 

