apiVersion: v1
kind: Service 
metadata:
  name: home-svc
  namespace: test-dev 
spec:
  type: ClusterIP
  selector:
    app: home 
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
