apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home
  name: home
  namespace: test-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      serviceAccountName: app-sa
      containers:
      - image: homeassistant/home-assistant
        name: home-assistant
        ports:
          - containerPort: 8123
