apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mariadb-deployment 
  namespace: test-dev 
  labels:
    app: data
    env: mariadb-deployment
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      env: mariadb-deployment
  template:
    metadata:
      name: mariadb-pod 
      labels:
        env: mariadb-deployment
    spec:
      serviceAccountName: app-sa
      containers:
        - name: mariadb 
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret-deployment 
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret-deployment
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret-deployment
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret-deployment
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
