apiVersion: v1
kind: Service 
metadata:
  name: mariadb-svc
  namespace: test-dev 
spec:
  selector:
    env: mariadb-deployment 
  ports:
    - name: mariadb-svc 
      port: 3306
      targetPort: 3306
  
