apiVersion: apps/v1
kind: Deployment 
metadata:
  name: myapp-deployment 
  namespace: test-dev 
  labels:
    tier: deployment 
    app: my-deploy 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod 
  template:
    metadata:
      name: my-pod
      labels:
        tier: pod
        app: pod 
    spec:
      containers:
        - name: nginx
          image: nginx
---
apiVersion: v1
kind: Service 
metadata:
  name: nginx-deploy 
  namespace: test-dev 
  labels:
    tier: service 
    app: app-service 
spec:
  selector:
    app: pod  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
