apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres-rs 
  namespace: test-dev 
  labels:
    tier: test 
    env: postgres-rs
spec:
  selector:
    matchLabels:
      env: postgres-rs 
  replicas: 5
  template:
    metadata:
      name: postgres-pod 
      labels:
        env: postgres-rs 
        tier: test 
    spec:
      containers:
        - name: postgres 
          image: postgres:latest 
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pw
                  key: POSTGRES_PASSWORD 
            
