apiVersion: apps/v1
kind: Deployment 
metadata:
  name: redhat
  namespace: test-dev 
  labels:
    app: redhat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redhat
  template:
    metadata:
      labels:
        app: redhat
    spec:
      serviceAccountName: app-sa
      containers:
        - name: redhat
          image: redhat/ubi8
          command: ["/bin/bash", "-c"]
          args: ["sleep infinity"]
