apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: my-rs
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      env: production
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx

