apiVersion: apps/v1
kind: Deployment 
metadata:
  name: wordpress-deploy 
  namespace: test-dev 
  labels:
    tier: test
    env: app 
spec:
  selector:
    matchLabels:
      tier: test
  replicas: 2
  template:
    metadata:
      name: wordpress-pod 
      labels:
        tier: test
    spec:
      containers:
        - name: wordpress 
          image: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-svc
            - name: WORDPRESS_DB_USER
              value: aero 
            - name: WORDPRESS_DB_PASSWORD
              value: aero 
            - name: WORDPRESS_DB_NAME
              value: aero
            - name: WORDPRESS_SITE_URL
              value: https://pw.heroaero.dev
            - name: WORDPRESS_HOME
              value: https://pw.heroaero.dev 
          ports:
            - containerPort: 80
