apiVersion: apps/v1
kind: Deployment 
metadata:
  name: wordpress-deploy 
  namespace: test-dev 
  labels:
    tier: test
    env: app 
spec:
  selector:
    matchLabels:
      tier: test
  replicas: 2
  template:
    metadata:
      name: wordpress-pod 
      labels:
        tier: test
    spec:
      serviceAccountName: app-sa
      containers:
        - name: wordpress 
          image: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wordpress 
                  key:  WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: WORDPRESS_DB_NAME
            - name: WORDPRESS_SITE_URL
              value: https://pw.heroaero.dev
            - name: WORDPRESS_HOME
              value: https://pw.heroaero.dev 
          ports:
            - containerPort: 80
