apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mariadb-rs 
  namespace: test-dev 
  labels:
    tier: test 
    env: data
spec:
  replicas: 2
  selector:
    matchLabels:
      env: data
  template: 
    metadata:
      name: mariadb-pod 
      labels:
        tier: data-pod 
        env: data
    spec:
      serviceAccountName: app-sa
      containers:
        - name: mariadb-pod 
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: mariadb-secret-rs 
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret-rs
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret-rs
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret-rs
                  key: MYSQL_PASSWORD
            - name: MYSQL_TCP_PORT
              value: "3306"
