apiVersion: v1
kind: Service 
metadata:
  name: mcraft-svc
  namespace: test-dev 
spec:
  type: NodePort
  selector:
    env: game 
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      nodePort: 31111
