apiVersion: external-secrets.io/v1
kind: ExternalSecret 
metadata:
  name: pgadmin-eso
  namespace: pgadmin 
spec:
  refreshInterval: 1m 
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore 
  target:
    name: pgadmin-secret 
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: pgadmin-secret 
