apiVersion: external-secrets.io/v1
kind: ExternalSecret 
metadata:
  name: cloudflared-external
  namespace: cloudflared 
spec:
  refreshInterval: 1m 
  secretStoreRef:
    name: secret-store
    kind: SecretStore 
  target:
    name: kube-secret 
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare-secret 
