apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secret-store
  namespace: cloudflared
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret 
            key: access-key 
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key 
